using NUnit.Framework;
using Smartest.Rounds;

namespace Smartest.Tests
{
    /// <summary>
    /// GENERATED by scratchpad/oracle.py — do not hand-edit.
    ///
    /// Every expected value here was computed by an independent Python model of the rule,
    /// not read out of the C#. If the two disagree, one of them is wrong and the test says
    /// so, instead of quietly agreeing with a bug.
    /// </summary>
    public class ResolverTests
    {
        private static RoundContext Ctx(int[] answers, int[] scores, int subRound)
        {
            int n = answers.Length;
            var s = scores ?? new int[n];
            var names = new string[n];
            for (int i = 0; i < n; i++) names[i] = "P" + (i + 1);
            return new RoundContext { PlayerCount = n, Answers = answers, Scores = s, Names = names, SubRound = subRound };
        }

        private static void Check(int id, int[] answers, int[] scores, int subRound,
            int[] expected, string key, bool expectContinue = false)
        {
            var def = RoundCatalog.CreateDefinition(RoundCatalog.Get(id));
            var r = ResolverRegistry.Resolve(def, Ctx(answers, scores, subRound));
            Assert.AreEqual(expected, r.Deltas, "round " + id + " deltas");
            Assert.AreEqual(key, r.OutcomeKey, "round " + id + " outcome key");
            Assert.AreEqual(expectContinue, r.ContinueSubRounds, "round " + id + " sub-round continuation");
            UnityEngine.Object.DestroyImmediate(def);
        }

        // ---- 1 TheButton ----
        [Test] public void C01_TheButton_AllGreen() => Check(1, new[] { 0, 0, 0 }, null, 1, new[] { 10, 10, 10 }, "allGreen");
        [Test] public void C01_TheButton_OneRedBetrays() => Check(1, new[] { 1, 0, 0 }, null, 1, new[] { 15, -5, -5 }, "someRed");
        [Test] public void C01_TheButton_TwoRedsGreensPay() => Check(1, new[] { 1, 1, 0, 0 }, null, 1, new[] { 15, 15, -5, -5 }, "someRed");
        [Test] public void C01_TheButton_AllRedCollapses() => Check(1, new[] { 1, 1, 1 }, null, 1, new[] { -10, -10, -10 }, "allRed");
        [Test] public void C01_TheButton_NoAnswerCountsGreen() => Check(1, new[] { 1, -1, 0 }, null, 1, new[] { 15, -5, -5 }, "someRed");
        // ---- 2 PickAPill ----
        [Test] public void C02_PickAPill_MinorityRedWins() => Check(2, new[] { 1, 0, 0, 0 }, null, 1, new[] { 8, 3, 3, 3 }, "redWins");
        [Test] public void C02_PickAPill_HalfRedFails() => Check(2, new[] { 1, 1, 0, 0 }, null, 1, new[] { 0, 0, 3, 3 }, "redFails");
        [Test] public void C02_PickAPill_NobodyTookRed() => Check(2, new[] { 0, 0, 0 }, null, 1, new[] { 3, 3, 3 }, "noRed");
        // ---- 3 TheSnap ----
        [Test] public void C03_TheSnap_ExactlyHalf() => Check(3, new[] { 1, 1, 0, 0 }, null, 1, new[] { 10, 10, -10, -10 }, "balanced");
        [Test] public void C03_TheSnap_HalfOfFive() => Check(3, new[] { 1, 1, 0, 0, 0 }, null, 1, new[] { 10, 10, -10, -10, -10 }, "balanced");
        [Test] public void C03_TheSnap_TooManyReds() => Check(3, new[] { 1, 1, 1, 0 }, null, 1, new[] { 0, 0, 0, 0 }, "unbalanced");
        [Test] public void C03_TheSnap_NoReds() => Check(3, new[] { 0, 0, 0, 0 }, null, 1, new[] { 0, 0, 0, 0 }, "unbalanced");
        // ---- 4 TheDoor ----
        [Test] public void C04_TheDoor_LoneSurvivor() => Check(4, new[] { 1, 1, 0 }, null, 1, new[] { 0, 0, 15 }, "one");
        [Test] public void C04_TheDoor_BothDrown() => Check(4, new[] { 0, 0, 1 }, null, 1, new[] { -5, -5, 0 }, "many");
        [Test] public void C04_TheDoor_NobodyClimbed() => Check(4, new[] { 1, 1, 1 }, null, 1, new[] { 0, 0, 0 }, "none");
        [Test] public void C04_TheDoor_SilenceIsNotClimbing() => Check(4, new[] { 1, 1, -1 }, null, 1, new[] { 0, 0, 0 }, "none");
        // ---- 5 RuleOne ----
        [Test] public void C05_RuleOne_AllDifferent() => Check(5, new[] { 1, 4, 7 }, null, 1, new[] { 5, 5, 5 }, "unique");
        [Test] public void C05_RuleOne_TwoMatched() => Check(5, new[] { 3, 3, 8 }, null, 1, new[] { 0, 0, 0 }, "dup");
        [Test] public void C05_RuleOne_SilenceStillCounts() => Check(5, new[] { 2, 5, -1 }, null, 1, new[] { 5, 5, 0 }, "unique");
        // ---- 7 LowestUnique ----
        [Test] public void C07_LowestUnique_LowestAloneWins() => Check(7, new[] { 2, 3, 3 }, null, 1, new[] { 15, 0, 0 }, "win");
        [Test] public void C07_LowestUnique_OneIsNotUnique() => Check(7, new[] { 1, 1, 4 }, null, 1, new[] { 0, 0, 15 }, "win");
        [Test] public void C07_LowestUnique_EverybodyMatched() => Check(7, new[] { 5, 5, 9, 9 }, null, 1, new[] { 0, 0, 0, 0 }, "none");
        // ---- 8 TwoThirds ----
        [Test] public void C08_TwoThirds_ClosestWins() => Check(8, new[] { 1, 5, 9 }, null, 1, new[] { 0, 10, 0 }, "win");
        [Test] public void C08_TwoThirds_TieSplits() => Check(8, new[] { 3, 3, 9 }, null, 1, new[] { 5, 5, 0 }, "win");
        // ---- 9 ThePot ----
        [Test] public void C09_ThePot_FreeRiderProfits() => Check(9, new[] { 10, 0, 0 }, new[] { 50, 50, 50 }, 1, new[] { -4, 6, 6 }, "reveal");
        [Test] public void C09_ThePot_EveryoneGivesEqually() => Check(9, new[] { 5, 5, 5 }, new[] { 50, 50, 50 }, 1, new[] { 5, 5, 5 }, "same");
        [Test] public void C09_ThePot_CantGiveWhatYouLack() => Check(9, new[] { 10, 0 }, new[] { 3, 40 }, 1, new[] { 0, 3 }, "reveal");
        // ---- 10 SilentAuction ----
        [Test] public void C10_SilentAuction_HighBidWins() => Check(10, new[] { 7, 3, 1 }, null, 1, new[] { 13, -3, -1 }, "reveal");
        [Test] public void C10_SilentAuction_TiedBidsSplit() => Check(10, new[] { 8, 8, 2 }, null, 1, new[] { 2, 2, -2 }, "reveal");
        [Test] public void C10_SilentAuction_NobodyBid() => Check(10, new[] { 0, 0, -1 }, null, 1, new[] { 0, 0, 0 }, "none");
        // ---- 11 Greedy ----
        [Test] public void C11_Greedy_UnderTheLimit() => Check(11, new[] { 6, 6, 6 }, null, 1, new[] { 6, 6, 6 }, "under");
        [Test] public void C11_Greedy_OneOverRuinsIt() => Check(11, new[] { 6, 6, 7 }, null, 1, new[] { 0, 0, 0 }, "over");
        // ---- 12 RateThisGame ----
        [Test] public void C12_RateThisGame_ExactlySeven() => Check(12, new[] { 7, 7, 7 }, null, 1, new[] { 10, 10, 10 }, "exact");
        [Test] public void C12_RateThisGame_AverageWorksToo() => Check(12, new[] { 10, 4, 7 }, null, 1, new[] { 10, 10, 10 }, "exact");
        [Test] public void C12_RateThisGame_OneHonestRating() => Check(12, new[] { 7, 7, 6 }, null, 1, new[] { 0, 0, 0 }, "miss");
        // ---- 13 TakeTheHit ----
        [Test] public void C13_TakeTheHit_LoneHeroIsPaid() => Check(13, new[] { 1, 0, 0 }, null, 1, new[] { 10, 5, 5 }, "one");
        [Test] public void C13_TakeTheHit_NobodyStepsUp() => Check(13, new[] { 0, 0, 0 }, null, 1, new[] { -5, -5, -5 }, "none");
        [Test] public void C13_TakeTheHit_HeroesCancelOut() => Check(13, new[] { 1, 1, 0 }, null, 1, new[] { -5, -5, 0 }, "many");
        // ---- 14 AttackTheLeader ----
        [Test] public void C14_AttackTheLeader_MobAttacks() => Check(14, new[] { 1, 1, 0 }, new[] { 30, 10, 10 }, 1, new[] { -18, -3, 0 }, "attack");
        [Test] public void C14_AttackTheLeader_LeaderJoinsIn() => Check(14, new[] { 1, 0, 0 }, new[] { 30, 10, 10 }, 1, new[] { -18, 0, 0 }, "attack");
        [Test] public void C14_AttackTheLeader_NobodyMoves() => Check(14, new[] { 0, 0, 0 }, new[] { 30, 10, 10 }, 1, new[] { 0, 0, 0 }, "none");
        // ---- 15 TheLever ----
        [Test] public void C15_TheLever_NobodyPullsYet() => Check(15, new[] { 0, 0, 0 }, null, 1, new[] { 0, 0, 0 }, "held", true);
        [Test] public void C15_TheLever_OnePullsRoundTwo() => Check(15, new[] { 1, 0, 0 }, null, 2, new[] { 10, 0, 0 }, "pulled");
        [Test] public void C15_TheLever_TwoSplitRoundThree() => Check(15, new[] { 1, 1, 0 }, null, 3, new[] { 7, 7, 0 }, "pulled");
        [Test] public void C15_TheLever_HeldToTheEnd() => Check(15, new[] { 0, 0, 0 }, null, 5, new[] { 20, 20, 20 }, "never");
        // ---- 16 Trolley ----
        [Test] public void C16_Trolley_SomeonePulls() => Check(16, new[] { 1, 0, 0 }, null, 1, new[] { -5, 0, 0 }, "someYes");
        [Test] public void C16_Trolley_NobodyPulls() => Check(16, new[] { 0, 0, 0 }, null, 1, new[] { -10, -10, -10 }, "none");
        // ---- 17 OneUp ----
        [Test] public void C17_OneUp_LoneHolderIsPaid() => Check(17, new[] { 1, 0, 0 }, null, 1, new[] { 10, 5, 5 }, "soloRed");
        [Test] public void C17_OneUp_SeveralHeldBack() => Check(17, new[] { 1, 1, 0 }, null, 1, new[] { 0, 0, 5 }, "someRed");
        [Test] public void C17_OneUp_EveryoneReached() => Check(17, new[] { 0, 0, 0 }, null, 1, new[] { 0, 0, 0 }, "allGreen");
        // ---- 18 IsThisADream ----
        [Test] public void C18_IsThisADream_MajorityYes() => Check(18, new[] { 1, 1, 0 }, null, 1, new[] { 3, 3, -3 }, "reveal");
        [Test] public void C18_IsThisADream_EvenSplit() => Check(18, new[] { 1, 1, 0, 0 }, null, 1, new[] { -1, -1, -1, -1 }, "tie");
        // ---- 19 Charity ----
        [Test] public void C19_Charity_HalfDonate() => Check(19, new[] { 1, 1, 0, 0 }, new[] { 10, 10, 10, 2 }, 1, new[] { 2, 2, 0, 6 }, "enough");
        [Test] public void C19_Charity_OnlyOneDonates() => Check(19, new[] { 1, 0, 0, 0 }, new[] { 10, 10, 10, 2 }, 1, new[] { -3, 0, 0, 3 }, "few");
        [Test] public void C19_Charity_NobodyDonates() => Check(19, new[] { 0, 0, 0 }, new[] { 10, 10, 2 }, 1, new[] { 0, 0, 0 }, "none");
        // ---- 20 PredictTheRoom ----
        [Test] public void C20_PredictTheRoom_ScoresLater() => Check(20, new[] { 2, 0, 3 }, null, 1, new[] { 0, 0, 0 }, "predicted");
        // ---- 21 TheGodfather ----
        [Test] public void C21_TheGodfather_UniqueLowest() => Check(21, new[] { 2, 4, 4 }, null, 1, new[] { 10, 0, 0 }, "unique");
        [Test] public void C21_TheGodfather_SharedLowest() => Check(21, new[] { 3, 3, 8 }, null, 1, new[] { -10, -10, 0 }, "shared");
        // ---- 22 Sus ----
        [Test] public void C22_Sus_MinorityWins() => Check(22, new[] { 1, 0, 0 }, null, 1, new[] { 10, 0, 0 }, "reveal");
        [Test] public void C22_Sus_EvenSplitPaysNobody() => Check(22, new[] { 1, 1, 0, 0 }, null, 1, new[] { 0, 0, 0, 0 }, "tie");
        // ---- 26 Pairs ----
        [Test] public void C26_Pairs_ExactlyTwoMatch() => Check(26, new[] { 4, 4, 9 }, null, 1, new[] { 10, 10, 0 }, "pairs");
        [Test] public void C26_Pairs_ThreeIsACrowd() => Check(26, new[] { 4, 4, 4 }, null, 1, new[] { 0, 0, 0 }, "none");
        [Test] public void C26_Pairs_TwoSeparatePairs() => Check(26, new[] { 4, 4, 9, 9 }, null, 1, new[] { 10, 10, 10, 10 }, "pairs");
        [Test] public void C26_Pairs_NobodyMatched() => Check(26, new[] { 1, 2, 3 }, null, 1, new[] { 0, 0, 0 }, "none");
        // ---- 27 Sacrifice ----
        [Test] public void C27_Sacrifice_HalfGive() => Check(27, new[] { 1, 1, 0, 0 }, null, 1, new[] { 10, 10, 15, 15 }, "enough");
        [Test] public void C27_Sacrifice_NotEnough() => Check(27, new[] { 1, 0, 0, 0 }, null, 1, new[] { -5, 0, 0, 0 }, "notEnough");
        [Test] public void C27_Sacrifice_NobodyGives() => Check(27, new[] { 0, 0, 0 }, null, 1, new[] { 0, 0, 0 }, "none");
        // ---- 28 Bandwagon ----
        [Test] public void C28_Bandwagon_BiggestGroupPays() => Check(28, new[] { 5, 5, 9 }, null, 1, new[] { 5, 5, 0 }, "crowd");
        [Test] public void C28_Bandwagon_Unanimous() => Check(28, new[] { 7, 7, 7 }, null, 1, new[] { 10, 10, 10 }, "unanimous");
        [Test] public void C28_Bandwagon_NoMatchesAtAll() => Check(28, new[] { 1, 2, 3 }, null, 1, new[] { 0, 0, 0 }, "none");
        [Test] public void C28_Bandwagon_TiedGroupsBothPay() => Check(28, new[] { 2, 2, 8, 8 }, null, 1, new[] { 5, 5, 5, 5 }, "crowd");

        // ---- 20 PredictTheRoom follow-up ----
        [Test]
        public void C20_PredictTheRoom_FollowUpScoresExactAndNearMisses()
        {
            var def = RoundCatalog.CreateDefinition(RoundCatalog.Get(20));
            var ctx = Ctx(new[] { 0, 0, 0, 0 }, null, 1);
            var r = PredictTheRoomResolver.ScoreFollowUp(def, new[] { 2, 3, 0, -1 }, 2, ctx);
            Assert.AreEqual(new[] { 5, 2, 0, 0 }, r.Deltas);
            Assert.AreEqual("followup", r.OutcomeKey);
            UnityEngine.Object.DestroyImmediate(def);
        }

        [Test]
        public void C20_PredictTheRoom_FollowUpWithNoWinners()
        {
            var def = RoundCatalog.CreateDefinition(RoundCatalog.Get(20));
            var ctx = Ctx(new[] { 0, 0 }, null, 1);
            var r = PredictTheRoomResolver.ScoreFollowUp(def, new[] { 8, 9 }, 2, ctx);
            Assert.AreEqual(new[] { 0, 0 }, r.Deltas);
            Assert.AreEqual("followupNone", r.OutcomeKey);
            UnityEngine.Object.DestroyImmediate(def);
        }

        // ---- Catalog invariants ----
        [Test]
        public void EveryRoundHasAResolverAndAShortRule()
        {
            foreach (var spec in RoundCatalog.All)
            {
                Assert.IsNotNull(ResolverRegistry.Get(spec.Resolver), "no resolver for round " + spec.Id);
                Assert.IsFalse(string.IsNullOrWhiteSpace(spec.Rule), "round " + spec.Id + " has no rule text");
                Assert.Less(spec.Rule.Length, 145,
                    "round " + spec.Id + ": the rule has to be readable in 2-4 seconds");
            }
        }

        [Test]
        public void EveryRoundHasALineForEveryOutcomeItCanProduce()
        {
            foreach (var spec in RoundCatalog.All)
                Assert.Greater(spec.Lines.Count, 0, "round " + spec.Id + " has no reveal lines");
        }

        [Test]
        public void ChallengeIdsAreUnique()
        {
            var seen = new System.Collections.Generic.HashSet<int>();
            foreach (var spec in RoundCatalog.AllChallenges())
                Assert.IsTrue(seen.Add(spec.Id), "duplicate challenge id " + spec.Id);
        }

        [Test] public void CatalogHasTheExpectedNumberOfSocialRounds()
            => Assert.AreEqual(24, RoundCatalog.All.Count);
    }
}
